jwt_signing_key: ABCD
jwt_token_validity: 604800000
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8088
  servlet:
    context-path: /randl2/adminApp
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/randl2_db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  setting:
    jwt:
      signingKey: ABCD
      issuer: SSD
      validity: 604800000
    admin:
      #管理员账号要尽量复杂，不和线上数据库里的账号重复
      account: superadmin
      password: '{noop}superadmin'
      defaultAppId: 1
      defaultRoleId: 1
    user:
      defaultAppId: 2
      defaultRoleId: 2